import { Box, Container } from "@mui/material"
import Head from "next/head"
import LandingTopSection from "../components/landing/LandingTopSection"
import IssuesSection from "../components/landing/IssuesSection"
import ObjectivesSection from "../components/landing/ObjectivesSection"
import GetStartedSection from "../components/landing/GetStartedSection"

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Warden NFT Ticket Platform</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Landing Top Section */}
      <LandingTopSection />
      <Box sx={{ height: 144 }} />

      {/* Issues Section */}
      <IssuesSection />
      <Box sx={{ height: 144 }} />

      {/* Objectives Section */}
      <ObjectivesSection />
      <Box sx={{ height: 144 }} />

      {/* Get Started Section */}
      <GetStartedSection />
    </Container>
  )
}
